-- MySQL Script generated by MySQL Workbench
-- Tue Dec  3 11:07:45 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';


-- -----------------------------------------------------
-- Table `ville`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ville`;

CREATE TABLE IF NOT EXISTS `ville` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `nom_reel` VARCHAR(45) NULL,
  `longitude` VARCHAR(45) NULL,
  `latitude` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `membre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `membre`;

CREATE TABLE IF NOT EXISTS `membre` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `pseudo` VARCHAR(45) NULL,
  `mdp` VARCHAR(45) NULL,
  `date_naissance` DATE NULL,
  `sexe` CHAR(5) NULL,
  `date_inscription` DATE NULL,
  `ville` INT NOT NULL,
  `role` ENUM('m', 'a') DEFAULT 'm',
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_membre_ville1`
    FOREIGN KEY (`ville`)
    REFERENCES `ville` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `site`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `site` ;

CREATE TABLE IF NOT EXISTS `site` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `lien` VARCHAR(45) NULL,
  `logo` VARCHAR(75) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `categorie` ;

CREATE TABLE IF NOT EXISTS `categorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nom_categorie` VARCHAR(45) NULL UNIQUE,
  `pere` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_categorie_categorie1`
    FOREIGN KEY (`pere`)
    REFERENCES `categorie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO `categorie` (nom_categorie, pere) VALUES ("femmes", 1);
INSERT INTO `categorie` (nom_categorie, pere) VALUES ("hommes", 2);
INSERT INTO `categorie` (nom_categorie, pere) VALUES ("enfants", 3);
-- -----------------------------------------------------
-- Table `taille`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taille` ;

CREATE TABLE IF NOT EXISTS `taille` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `taille` VARCHAR(45) NULL,
  `categorie` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_taille_categorie1`
    FOREIGN KEY (`categorie`)
    REFERENCES `categorie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `marque`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `marque` ;

CREATE TABLE IF NOT EXISTS `marque` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marque` VARCHAR(30) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `article`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `article` ;

CREATE TABLE IF NOT EXISTS `article` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(400) NULL,
  `prix` DECIMAL(2) NULL,
  `keyword` VARCHAR(45) NULL,
  `couleur` VARCHAR(45) NULL,
  `etat` ENUM('Neuf, avec étiquette', 'Neuf', 'Très bon état', 'Bon état', 'Satisfaisant') NULL,
  `photo1` VARCHAR(45) NULL,
  `photo2` VARCHAR(45) NULL,
  `photo3` VARCHAR(45) NULL,
  `taille` INT NOT NULL,
  `categorie` INT NOT NULL,
  `site` INT NOT NULL,
  `marque` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_article_site1`
    FOREIGN KEY (`site`)
    REFERENCES `site` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_article_taille1`
    FOREIGN KEY (`taille`)
    REFERENCES `taille` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_article_categorie1`
    FOREIGN KEY (`categorie`)
    REFERENCES `categorie` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_article_marque1`
    FOREIGN KEY (`marque`)
    REFERENCES `marque` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `favori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `favori` ;

CREATE TABLE IF NOT EXISTS `favori` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date_favori` DATE NULL,
  `flag` ENUM('f', 'h') NULL,
  `article` INT NOT NULL,
  `membre` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_favori_article1`
    FOREIGN KEY (`article`)
    REFERENCES `article` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_favori_membre1`
    FOREIGN KEY (`membre`)
    REFERENCES `membre` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recherche`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recherche` ;

CREATE TABLE IF NOT EXISTS `recherche` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `terme` VARCHAR(45) NULL,
  `membre` INT NOT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_recherche_membre1`
    FOREIGN KEY (`membre`)
    REFERENCES `membre` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
